version: '3.8'

networks:
  kong-net:
    external: false

services:
  api:
    build: .
    ports:
      - "3000:3000"
  cms:
    container_name: cms
    build: 
      context: cms
      dockerfile: ./Dockerfile
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      JWT_SECRET: FLBqKgI+Pe9kyy54LrQsvQ==
      APP_KEYS: MNjRCoOTfeCDuAdsPRmkig==,rMDOiWJ3OtZ0a+kFTVPaJg==,i6Zw4lT8w71EJnFjuxi6HA==,KYNepElHb62jaFzJxSQXkg==
      API_TOKEN_SALT: FLBqKgI+Pe9kyy54LrQsvQ==
      ADMIN_JWT_SECRET: yV7vQF4oKkTdjmoXChn2nA==
      TRANSFER_TOKEN_SALT: /3J9ZOAIUB2pAeNwzno9lA==
      NODE_ENV: production

  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    volumes:
      - ./kong/declarative:/kong/declarative/
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - "KONG_DATABASE=off"
      - "KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
    depends_on:
      - cms
      - api
